clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/NYSE/A.py &
python3 /home/ubuntu/Desktop/NYSE/AA.py &
python3 /home/ubuntu/Desktop/NYSE/AAC.py &
python3 /home/ubuntu/Desktop/NYSE/AACG.py &
python3 /home/ubuntu/Desktop/NYSE/AACI.py &
python3 /home/ubuntu/Desktop/NYSE/AACIU.py &
python3 /home/ubuntu/Desktop/NYSE/AACIW.py &
python3 /home/ubuntu/Desktop/NYSE/AADI.py &
python3 /home/ubuntu/Desktop/NYSE/AAIC.py &
python3 /home/ubuntu/Desktop/NYSE/AAL.py &
python3 /home/ubuntu/Desktop/NYSE/AAMC.py &
python3 /home/ubuntu/Desktop/NYSE/AAME.py &
python3 /home/ubuntu/Desktop/NYSE/AAN.py &
python3 /home/ubuntu/Desktop/NYSE/AAOI.py &
python3 /home/ubuntu/Desktop/NYSE/AAON.py &
python3 /home/ubuntu/Desktop/NYSE/AAP.py &
python3 /home/ubuntu/Desktop/NYSE/AAPL.py &
python3 /home/ubuntu/Desktop/NYSE/AAQC.py &
python3 /home/ubuntu/Desktop/NYSE/AAT.py &
python3 /home/ubuntu/Desktop/NYSE/AATC.py &
python3 /home/ubuntu/Desktop/NYSE/AAU.py &
python3 /home/ubuntu/Desktop/NYSE/AAWW.py &
python3 /home/ubuntu/Desktop/NYSE/AB.py &
python3 /home/ubuntu/Desktop/NYSE/ABB.py &
python3 /home/ubuntu/Desktop/NYSE/ABBV.py &
python3 /home/ubuntu/Desktop/NYSE/ABC.py &
python3 /home/ubuntu/Desktop/NYSE/ABCB.py &
python3 /home/ubuntu/Desktop/NYSE/ABCL.py &
python3 /home/ubuntu/Desktop/NYSE/ABCM.py &
python3 /home/ubuntu/Desktop/NYSE/ABEO.py &
python3 /home/ubuntu/Desktop/NYSE/ABEV.py &
python3 /home/ubuntu/Desktop/NYSE/ABG.py &
python3 /home/ubuntu/Desktop/NYSE/ABGI.py &
python3 /home/ubuntu/Desktop/NYSE/ABIO.py &
python3 /home/ubuntu/Desktop/NYSE/ABM.py &
python3 /home/ubuntu/Desktop/NYSE/ABMD.py &
python3 /home/ubuntu/Desktop/NYSE/ABNB.py &
python3 /home/ubuntu/Desktop/NYSE/ABOS.py &
python3 /home/ubuntu/Desktop/NYSE/ABR.py &
python3 /home/ubuntu/Desktop/NYSE/ABSI.py &
python3 /home/ubuntu/Desktop/NYSE/ABST.py &
python3 /home/ubuntu/Desktop/NYSE/ABT.py &
python3 /home/ubuntu/Desktop/NYSE/ABTX.py &
python3 /home/ubuntu/Desktop/NYSE/ABUS.py &
python3 /home/ubuntu/Desktop/NYSE/ABVC.py &
python3 /home/ubuntu/Desktop/NYSE/AC.py &
python3 /home/ubuntu/Desktop/NYSE/ACA.py &
python3 /home/ubuntu/Desktop/NYSE/ACAB.py &
python3 /home/ubuntu/Desktop/NYSE/ACABU.py &
python3 /home/ubuntu/Desktop/NYSE/ACAD.py &
python3 /home/ubuntu/Desktop/NYSE/ACAH.py &
python3 /home/ubuntu/Desktop/NYSE/ACAHU.py &
python3 /home/ubuntu/Desktop/NYSE/ACAHW.py &
python3 /home/ubuntu/Desktop/NYSE/ACAQ.py &
python3 /home/ubuntu/Desktop/NYSE/ACAXR.py &
python3 /home/ubuntu/Desktop/NYSE/ACAXU.py &
python3 /home/ubuntu/Desktop/NYSE/ACAXW.py &
python3 /home/ubuntu/Desktop/NYSE/ACEL.py &
python3 /home/ubuntu/Desktop/NYSE/ACER.py &
python3 /home/ubuntu/Desktop/NYSE/ACET.py &
python3 /home/ubuntu/Desktop/NYSE/ACEV.py &
python3 /home/ubuntu/Desktop/NYSE/ACEVU.py &
python3 /home/ubuntu/Desktop/NYSE/ACGL.py &
python3 /home/ubuntu/Desktop/NYSE/ACGLN.py &
python3 /home/ubuntu/Desktop/NYSE/ACGLO.py &
python3 /home/ubuntu/Desktop/NYSE/ACH.py &
python3 /home/ubuntu/Desktop/NYSE/ACHC.py &
python3 /home/ubuntu/Desktop/NYSE/ACHL.py &
python3 /home/ubuntu/Desktop/NYSE/ACHR.py &
python3 /home/ubuntu/Desktop/NYSE/ACHV.py &
python3 /home/ubuntu/Desktop/NYSE/ACI.py &
python3 /home/ubuntu/Desktop/NYSE/ACII.py &
python3 /home/ubuntu/Desktop/NYSE/ACIU.py &
python3 /home/ubuntu/Desktop/NYSE/ACIW.py &
python3 /home/ubuntu/Desktop/NYSE/ACM.py &
python3 /home/ubuntu/Desktop/NYSE/ACMR.py &
python3 /home/ubuntu/Desktop/NYSE/ACN.py &
python3 /home/ubuntu/Desktop/NYSE/ACNB.py &
python3 /home/ubuntu/Desktop/NYSE/ACON.py &
python3 /home/ubuntu/Desktop/NYSE/ACONW.py &
python3 /home/ubuntu/Desktop/NYSE/ACOR.py &
python3 /home/ubuntu/Desktop/NYSE/ACP.py &
python3 /home/ubuntu/Desktop/NYSE/ACQR.py &
python3 /home/ubuntu/Desktop/NYSE/ACQRU.py &
python3 /home/ubuntu/Desktop/NYSE/ACR.py &
python3 /home/ubuntu/Desktop/NYSE/ACRO.py &
python3 /home/ubuntu/Desktop/NYSE/ACRS.py &
python3 /home/ubuntu/Desktop/NYSE/ACRX.py &
python3 /home/ubuntu/Desktop/NYSE/ACST.py &
python3 /home/ubuntu/Desktop/NYSE/ACT.py &
python3 /home/ubuntu/Desktop/NYSE/ACTD.py &
python3 /home/ubuntu/Desktop/NYSE/ACU.py &
python3 /home/ubuntu/Desktop/NYSE/ACV.py &
python3 /home/ubuntu/Desktop/NYSE/ACVA.py &
python3 /home/ubuntu/Desktop/NYSE/ACXP.py &
python3 /home/ubuntu/Desktop/NYSE/ADAG.py &
python3 /home/ubuntu/Desktop/NYSE/ADAL.py &
python3 /home/ubuntu/Desktop/NYSE/ADAP.py &
python3 /home/ubuntu/Desktop/NYSE/ADBE.py &
python3 /home/ubuntu/Desktop/NYSE/ADC.py &
python3 /home/ubuntu/Desktop/NYSE/ADCT.py &
python3 /home/ubuntu/Desktop/NYSE/ADER.py &
python3 /home/ubuntu/Desktop/NYSE/ADERW.py &
python3 /home/ubuntu/Desktop/NYSE/ADES.py &
python3 /home/ubuntu/Desktop/NYSE/ADEX.py &
python3 /home/ubuntu/Desktop/NYSE/ADGI.py &
python3 /home/ubuntu/Desktop/NYSE/ADI.py &
python3 /home/ubuntu/Desktop/NYSE/ADIL.py &
python3 /home/ubuntu/Desktop/NYSE/ADM.py &
python3 /home/ubuntu/Desktop/NYSE/ADMA.py &
python3 /home/ubuntu/Desktop/NYSE/ADMP.py &
python3 /home/ubuntu/Desktop/NYSE/ADN.py &
python3 /home/ubuntu/Desktop/NYSE/ADNT.py &
python3 /home/ubuntu/Desktop/NYSE/ADOC.py &
python3 /home/ubuntu/Desktop/NYSE/ADOCR.py &
python3 /home/ubuntu/Desktop/NYSE/ADOCW.py &
python3 /home/ubuntu/Desktop/NYSE/ADP.py &
python3 /home/ubuntu/Desktop/NYSE/ADPT.py &
python3 /home/ubuntu/Desktop/NYSE/ADRA.py &
python3 /home/ubuntu/Desktop/NYSE/ADRT.py &
python3 /home/ubuntu/Desktop/NYSE/ADSE.py &
python3 /home/ubuntu/Desktop/NYSE/ADSEW.py &
python3 /home/ubuntu/Desktop/NYSE/ADSK.py &
python3 /home/ubuntu/Desktop/NYSE/ADT.py &
python3 /home/ubuntu/Desktop/NYSE/ADTH.py &
python3 /home/ubuntu/Desktop/NYSE/ADTHW.py &
python3 /home/ubuntu/Desktop/NYSE/ADTN.py &
python3 /home/ubuntu/Desktop/NYSE/ADTX.py &
python3 /home/ubuntu/Desktop/NYSE/ADUS.py &
python3 /home/ubuntu/Desktop/NYSE/ADV.py &
python3 /home/ubuntu/Desktop/NYSE/ADVM.py &
python3 /home/ubuntu/Desktop/NYSE/ADX.py &
python3 /home/ubuntu/Desktop/NYSE/ADXN.py &
python3 /home/ubuntu/Desktop/NYSE/AE.py &
python3 /home/ubuntu/Desktop/NYSE/AEAC.py &
python3 /home/ubuntu/Desktop/NYSE/AEE.py &
python3 /home/ubuntu/Desktop/NYSE/AEF.py &
python3 /home/ubuntu/Desktop/NYSE/AEFC.py &
python3 /home/ubuntu/Desktop/NYSE/AEG.py &
python3 /home/ubuntu/Desktop/NYSE/AEI.py &
python3 /home/ubuntu/Desktop/NYSE/AEIS.py &
python3 /home/ubuntu/Desktop/NYSE/AEL.py &
python3 /home/ubuntu/Desktop/NYSE/AEM.py &
python3 /home/ubuntu/Desktop/NYSE/AEMD.py &
python3 /home/ubuntu/Desktop/NYSE/AENZ.py &
python3 /home/ubuntu/Desktop/NYSE/AEO.py &
python3 /home/ubuntu/Desktop/NYSE/AEP.py &
python3 /home/ubuntu/Desktop/NYSE/AEPPZ.py &
python3 /home/ubuntu/Desktop/NYSE/AER.py &
python3 /home/ubuntu/Desktop/NYSE/AERC.py &
python3 /home/ubuntu/Desktop/NYSE/AERI.py &
python3 /home/ubuntu/Desktop/NYSE/AES.py &
python3 /home/ubuntu/Desktop/NYSE/AESC.py &
python3 /home/ubuntu/Desktop/NYSE/AESC.py &
python3 /home/ubuntu/Desktop/NYSE/AEVA.py &
python3 /home/ubuntu/Desktop/NYSE/AESE.py &
python3 /home/ubuntu/Desktop/NYSE/AEY.py &
python3 /home/ubuntu/Desktop/NYSE/AEYE.py &
python3 /home/ubuntu/Desktop/NYSE/AEZS.py &
python3 /home/ubuntu/Desktop/NYSE/AFAC.py &
python3 /home/ubuntu/Desktop/NYSE/AFACW.py &
python3 /home/ubuntu/Desktop/NYSE/AFAQ.py &
python3 /home/ubuntu/Desktop/NYSE/AFAQU.py &
python3 /home/ubuntu/Desktop/NYSE/AFAQW.py &
python3 /home/ubuntu/Desktop/NYSE/AFB.py &
python3 /home/ubuntu/Desktop/NYSE/AFBI.py &
python3 /home/ubuntu/Desktop/NYSE/AFCG.py &
python3 /home/ubuntu/Desktop/NYSE/AFG.py &
python3 /home/ubuntu/Desktop/NYSE/AFGB.py &
python3 /home/ubuntu/Desktop/NYSE/AFGC.py &
python3 /home/ubuntu/Desktop/NYSE/AFGD.py &
python3 /home/ubuntu/Desktop/NYSE/AFGE.py &
python3 /home/ubuntu/Desktop/NYSE/AFI.py &
python3 /home/ubuntu/Desktop/NYSE/AFIB.py &
python3 /home/ubuntu/Desktop/NYSE/AFL.py &
python3 /home/ubuntu/Desktop/NYSE/AFMD.py &
python3 /home/ubuntu/Desktop/NYSE/AFRM.py &
python3 /home/ubuntu/Desktop/NYSE/AFT.py &
python3 /home/ubuntu/Desktop/NYSE/AFTR.py &
python3 /home/ubuntu/Desktop/NYSE/AFYA.py &
python3 /home/ubuntu/Desktop/NYSE/AG.py &
python3 /home/ubuntu/Desktop/NYSE/AGAC.py &
python3 /home/ubuntu/Desktop/NYSE/AGBA.py &
python3 /home/ubuntu/Desktop/NYSE/AGBAR.py &
python3 /home/ubuntu/Desktop/NYSE/AGBAW.py &
python3 /home/ubuntu/Desktop/NYSE/AGCB.py &
python3 /home/ubuntu/Desktop/NYSE/AGCO.py &
python3 /home/ubuntu/Desktop/NYSE/AGD.py &
python3 /home/ubuntu/Desktop/NYSE/AGE.py &
python3 /home/ubuntu/Desktop/NYSE/AGEN.py &
python3 /home/ubuntu/Desktop/NYSE/AGFS.py &
python3 /home/ubuntu/Desktop/NYSE/AGFY.py &
python3 /home/ubuntu/Desktop/NYSE/AGGR.py &
python3 /home/ubuntu/Desktop/NYSE/AGGRU.py &
python3 /home/ubuntu/Desktop/NYSE/AGI.py &
python3 /home/ubuntu/Desktop/NYSE/AGIL.py &
python3 /home/ubuntu/Desktop/NYSE/AGILW.py &
python3 /home/ubuntu/Desktop/NYSE/AGIO.py &
python3 /home/ubuntu/Desktop/NYSE/AGL.py &
python3 /home/ubuntu/Desktop/NYSE/AGLE.py &
python3 /home/ubuntu/Desktop/NYSE/AGM.py &
python3 /home/ubuntu/Desktop/NYSE/AGMH.py &
python3 /home/ubuntu/Desktop/NYSE/AGNC.py &
python3 /home/ubuntu/Desktop/NYSE/AGNCM.py &
python3 /home/ubuntu/Desktop/NYSE/AGNCN.py &
python3 /home/ubuntu/Desktop/NYSE/AGNCO.py &
python3 /home/ubuntu/Desktop/NYSE/AGNCP.py &
python3 /home/ubuntu/Desktop/NYSE/AGO.py &
python3 /home/ubuntu/Desktop/NYSE/AGR.py &
python3 /home/ubuntu/Desktop/NYSE/AGRI.py &
python3 /home/ubuntu/Desktop/NYSE/AGRIW.py &
python3 /home/ubuntu/Desktop/NYSE/AGRO.py &
python3 /home/ubuntu/Desktop/NYSE/AGRX.py &
python3 /home/ubuntu/Desktop/NYSE/AGS.py &
python3 /home/ubuntu/Desktop/NYSE/AGTC.py &
python3 /home/ubuntu/Desktop/NYSE/AGTI.py &
python3 /home/ubuntu/Desktop/NYSE/AGX.py &
python3 /home/ubuntu/Desktop/NYSE/AGYS.py &
python3 /home/ubuntu/Desktop/NYSE/AHCO.py &
python3 /home/ubuntu/Desktop/NYSE/AHG.py &
python3 /home/ubuntu/Desktop/NYSE/AHH.py &
python3 /home/ubuntu/Desktop/NYSE/AHI.py &
python3 /home/ubuntu/Desktop/NYSE/AHPA.py &
python3 /home/ubuntu/Desktop/NYSE/AHPAU.py &
python3 /home/ubuntu/Desktop/NYSE/AHPAW.py &
python3 /home/ubuntu/Desktop/NYSE/AHPI.py &
python3 /home/ubuntu/Desktop/NYSE/AHRN.py &
python3 /home/ubuntu/Desktop/NYSE/AHRNU.py &
python3 /home/ubuntu/Desktop/NYSE/AHT.py &
python3 /home/ubuntu/Desktop/NYSE/AI.py &
python3 /home/ubuntu/Desktop/NYSE/AIB.py &
python3 /home/ubuntu/Desktop/NYSE/AIC.py &
python3 /home/ubuntu/Desktop/NYSE/AIF.py &
python3 /home/ubuntu/Desktop/NYSE/AIG.py &
python3 /home/ubuntu/Desktop/NYSE/AIH.py &
python3 /home/ubuntu/Desktop/NYSE/AIHS.py &
python3 /home/ubuntu/Desktop/NYSE/AIKI.py &
python3 /home/ubuntu/Desktop/NYSE/AIM.py &
python3 /home/ubuntu/Desktop/NYSE/AIMAU.py &
python3 /home/ubuntu/Desktop/NYSE/AIMC.py &
python3 /home/ubuntu/Desktop/NYSE/AIN.py &
python3 /home/ubuntu/Desktop/NYSE/AINC.py &
python3 /home/ubuntu/Desktop/NYSE/AINV.py &
python3 /home/ubuntu/Desktop/NYSE/AIO.py &
python3 /home/ubuntu/Desktop/NYSE/AIO.py &
python3 /home/ubuntu/Desktop/NYSE/AIP.py &
python3 /home/ubuntu/Desktop/NYSE/AIR.py &
python3 /home/ubuntu/Desktop/NYSE/AIRC.py &
python3 /home/ubuntu/Desktop/NYSE/AIRG.py &
python3 /home/ubuntu/Desktop/NYSE/AIRI.py &
python3 /home/ubuntu/Desktop/NYSE/AIRS.py &
python3 /home/ubuntu/Desktop/NYSE/AIRT.py &
python3 /home/ubuntu/Desktop/NYSE/AIRTP.py &
python3 /home/ubuntu/Desktop/NYSE/AIT.py &
python3 /home/ubuntu/Desktop/NYSE/AIU.py &
python3 /home/ubuntu/Desktop/NYSE/AIV.py &
python3 /home/ubuntu/Desktop/NYSE/AIZ.py &
python3 /home/ubuntu/Desktop/NYSE/AIZN.py &
python3 /home/ubuntu/Desktop/NYSE/AJG.py &
python3 /home/ubuntu/Desktop/NYSE/AJRD.py &
python3 /home/ubuntu/Desktop/NYSE/AJX.py &
python3 /home/ubuntu/Desktop/NYSE/AJXA.py &
python3 /home/ubuntu/Desktop/NYSE/AKA.py &
python3 /home/ubuntu/Desktop/NYSE/AKAM.py &
python3 /home/ubuntu/Desktop/NYSE/AKAN.py &
python3 /home/ubuntu/Desktop/NYSE/AKBA.py &
python3 /home/ubuntu/Desktop/NYSE/AKIC.py &
python3 /home/ubuntu/Desktop/NYSE/AKR.py &
python3 /home/ubuntu/Desktop/NYSE/AKRO.py &
python3 /home/ubuntu/Desktop/NYSE/AKTS.py &
python3 /home/ubuntu/Desktop/NYSE/AKTX.py &
python3 /home/ubuntu/Desktop/NYSE/AKU.py &
python3 /home/ubuntu/Desktop/NYSE/AKUS.py &
python3 /home/ubuntu/Desktop/NYSE/AKYA.py &
python3 /home/ubuntu/Desktop/NYSE/ALB.py &
python3 /home/ubuntu/Desktop/NYSE/ALBO.py &
python3 /home/ubuntu/Desktop/NYSE/ALC.py &
python3 /home/ubuntu/Desktop/NYSE/ALCC.py &
python3 /home/ubuntu/Desktop/NYSE/ALCO.py &
python3 /home/ubuntu/Desktop/NYSE/ALDX.py &
python3 /home/ubuntu/Desktop/NYSE/ALE.py &
python3 /home/ubuntu/Desktop/NYSE/ALEC.py &
python3 /home/ubuntu/Desktop/NYSE/ALEX.py &
python3 /home/ubuntu/Desktop/NYSE/ALF.py &
python3 /home/ubuntu/Desktop/NYSE/ALFIW.py &
python3 /home/ubuntu/Desktop/NYSE/ALG.py &
python3 /home/ubuntu/Desktop/NYSE/ALGM.py &
python3 /home/ubuntu/Desktop/NYSE/ALGN.py &
python3 /home/ubuntu/Desktop/NYSE/ALGS.py &
python3 /home/ubuntu/Desktop/NYSE/ALGT.py &
python3 /home/ubuntu/Desktop/NYSE/ALHC.py &
python3 /home/ubuntu/Desktop/NYSE/ALIT.py &
python3 /home/ubuntu/Desktop/NYSE/ALJJ.py &
python3 /home/ubuntu/Desktop/NYSE/ALK.py &
python3 /home/ubuntu/Desktop/NYSE/ALKS.py &
python3 /home/ubuntu/Desktop/NYSE/ALLE.py &
python3 /home/ubuntu/Desktop/NYSE/ALLG.py &
python3 /home/ubuntu/Desktop/NYSE/ALLK.py &
python3 /home/ubuntu/Desktop/NYSE/ALLO.py &
python3 /home/ubuntu/Desktop/NYSE/ALLR.py &
python3 /home/ubuntu/Desktop/NYSE/ALLT.py &
python3 /home/ubuntu/Desktop/NYSE/ALLY.py &
python3 /home/ubuntu/Desktop/NYSE/ALNA.py &
python3 /home/ubuntu/Desktop/NYSE/ALNY.py &
python3 /home/ubuntu/Desktop/NYSE/ALOR.py &
python3 /home/ubuntu/Desktop/NYSE/ALORU.py &
python3 /home/ubuntu/Desktop/NYSE/ALORW.py &
python3 /home/ubuntu/Desktop/NYSE/ALOT.py &
python3 /home/ubuntu/Desktop/NYSE/ALPA.py &
python3 /home/ubuntu/Desktop/NYSE/ALPAW.py &
python3 /home/ubuntu/Desktop/NYSE/ALPN.py &
python3 /home/ubuntu/Desktop/NYSE/ALPP.py &
python3 /home/ubuntu/Desktop/NYSE/ALR.py &
python3 /home/ubuntu/Desktop/NYSE/ALRM.py &
python3 /home/ubuntu/Desktop/NYSE/ALRN.py &
python3 /home/ubuntu/Desktop/NYSE/ALRS.py &
python3 /home/ubuntu/Desktop/NYSE/ALSA.py &
python3 /home/ubuntu/Desktop/NYSE/ALSAR.py &
python3 /home/ubuntu/Desktop/NYSE/ALSAW.py &
python3 /home/ubuntu/Desktop/NYSE/ALSN.py &
python3 /home/ubuntu/Desktop/NYSE/ALT.py &
python3 /home/ubuntu/Desktop/NYSE/ALTG.py &
python3 /home/ubuntu/Desktop/NYSE/ALTO.py &
python3 /home/ubuntu/Desktop/NYSE/ALTR.py &
python3 /home/ubuntu/Desktop/NYSE/ALTU.py &
python3 /home/ubuntu/Desktop/NYSE/ALTUU.py &
python3 /home/ubuntu/Desktop/NYSE/ALTUW.py &
python3 /home/ubuntu/Desktop/NYSE/ALV.py &
python3 /home/ubuntu/Desktop/NYSE/ALVR.py &
python3 /home/ubuntu/Desktop/NYSE/ALX.py &
python3 /home/ubuntu/Desktop/NYSE/ALXO.py &
python3 /home/ubuntu/Desktop/NYSE/ALYA.py &
python3 /home/ubuntu/Desktop/NYSE/ALZN.py &
python3 /home/ubuntu/Desktop/NYSE/AM.py &
python3 /home/ubuntu/Desktop/NYSE/AMAL.py &
python3 /home/ubuntu/Desktop/NYSE/AMAM.py &
python3 /home/ubuntu/Desktop/NYSE/AMAO.py &
python3 /home/ubuntu/Desktop/NYSE/AMAOW.py &
python3 /home/ubuntu/Desktop/NYSE/AMAT.py &
python3 /home/ubuntu/Desktop/NYSE/AMBA.py &
python3 /home/ubuntu/Desktop/NYSE/AMBC.py &
python3 /home/ubuntu/Desktop/NYSE/AMBO.py &
python3 /home/ubuntu/Desktop/NYSE/AMBP.py &
python3 /home/ubuntu/Desktop/NYSE/AMC.py &
python3 /home/ubuntu/Desktop/NYSE/AMCI.py &
python3 /home/ubuntu/Desktop/NYSE/AMCIW.py &
python3 /home/ubuntu/Desktop/NYSE/AMCR.py &
python3 /home/ubuntu/Desktop/NYSE/AMCX.py &
python3 /home/ubuntu/Desktop/NYSE/AMD.py &
python3 /home/ubuntu/Desktop/NYSE/AME.py &
python3 /home/ubuntu/Desktop/NYSE/AMED.py &
python3 /home/ubuntu/Desktop/NYSE/AMEH.py &
python3 /home/ubuntu/Desktop/NYSE/AMG.py &
python3 /home/ubuntu/Desktop/NYSE/AMGN.py &
python3 /home/ubuntu/Desktop/NYSE/AMH.py &
python3 /home/ubuntu/Desktop/NYSE/AMK.py &
python3 /home/ubuntu/Desktop/NYSE/AMKR.py &
python3 /home/ubuntu/Desktop/NYSE/AMLX.py &
python3 /home/ubuntu/Desktop/NYSE/AMN.py &
python3 /home/ubuntu/Desktop/NYSE/AMNB.py &
python3 /home/ubuntu/Desktop/NYSE/AMOT.py &
python3 /home/ubuntu/Desktop/NYSE/AMOV.py &
python3 /home/ubuntu/Desktop/NYSE/AMP.py &
python3 /home/ubuntu/Desktop/NYSE/AMPE.py &
python3 /home/ubuntu/Desktop/NYSE/AMPG.py &
python3 /home/ubuntu/Desktop/NYSE/AMPGW.py &
python3 /home/ubuntu/Desktop/NYSE/AMPH.py &
python3 /home/ubuntu/Desktop/NYSE/AMPI.py &
python3 /home/ubuntu/Desktop/NYSE/AMPL.py &
python3 /home/ubuntu/Desktop/NYSE/AMPS.py &
python3 /home/ubuntu/Desktop/NYSE/AMPY.py &
python3 /home/ubuntu/Desktop/NYSE/AMR.py &
python3 /home/ubuntu/Desktop/NYSE/AMRC.py &
python3 /home/ubuntu/Desktop/NYSE/AMRK.py &
python3 /home/ubuntu/Desktop/NYSE/AMRN.py &
python3 /home/ubuntu/Desktop/NYSE/AMRS.py &
python3 /home/ubuntu/Desktop/NYSE/AMRX.py &
python3 /home/ubuntu/Desktop/NYSE/AMS.py &
python3 /home/ubuntu/Desktop/NYSE/AMSC.py &
python3 /home/ubuntu/Desktop/NYSE/AMSF.py &
python3 /home/ubuntu/Desktop/NYSE/AMST.py &
python3 /home/ubuntu/Desktop/NYSE/AMSWA.py &
python3 /home/ubuntu/Desktop/NYSE/AMT.py &
python3 /home/ubuntu/Desktop/NYSE/AMTB.py &
python3 /home/ubuntu/Desktop/NYSE/AMTD.py &
python3 /home/ubuntu/Desktop/NYSE/AMTI.py &
python3 /home/ubuntu/Desktop/NYSE/AMTX.py &
python3 /home/ubuntu/Desktop/NYSE/AMWD.py &
python3 /home/ubuntu/Desktop/NYSE/AMWL.py &
python3 /home/ubuntu/Desktop/NYSE/AMX.py &
python3 /home/ubuntu/Desktop/NYSE/AMYT.py &
python3 /home/ubuntu/Desktop/NYSE/AMZN.py &
python3 /home/ubuntu/Desktop/NYSE/AN.py &
python3 /home/ubuntu/Desktop/NYSE/ANAB.py &
python3 /home/ubuntu/Desktop/NYSE/ANAC.py &
python3 /home/ubuntu/Desktop/NYSE/ANAT.py &
python3 /home/ubuntu/Desktop/NYSE/ANDE.py &
python3 /home/ubuntu/Desktop/NYSE/ANEB.py &
python3 /home/ubuntu/Desktop/NYSE/ANET.py &
python3 /home/ubuntu/Desktop/NYSE/ANF.py &
python3 /home/ubuntu/Desktop/NYSE/ANGH.py &
python3 /home/ubuntu/Desktop/NYSE/ANDE.py &
python3 /home/ubuntu/Desktop/NYSE/ANEB.py &
python3 /home/ubuntu/Desktop/NYSE/ANET.py &
python3 /home/ubuntu/Desktop/NYSE/ANF.py &
python3 /home/ubuntu/Desktop/NYSE/ANGH.py &
python3 /home/ubuntu/Desktop/NYSE/ANGHW.py &
python3 /home/ubuntu/Desktop/NYSE/ANGI.py &
python3 /home/ubuntu/Desktop/NYSE/ANGN.py &
python3 /home/ubuntu/Desktop/NYSE/ANGO.py &
python3 /home/ubuntu/Desktop/NYSE/ANIK.py &
python3 /home/ubuntu/Desktop/NYSE/ANIP.py &
python3 /home/ubuntu/Desktop/NYSE/ANIX.py &
python3 /home/ubuntu/Desktop/NYSE/ANPC.py &
python3 /home/ubuntu/Desktop/NYSE/ANSS.py &
python3 /home/ubuntu/Desktop/NYSE/ANTE.py &
python3 /home/ubuntu/Desktop/NYSE/ANTM.py &
python3 /home/ubuntu/Desktop/NYSE/ANTX.py &
python3 /home/ubuntu/Desktop/NYSE/ANVS.py &
python3 /home/ubuntu/Desktop/NYSE/ANY.py &
python3 /home/ubuntu/Desktop/NYSE/ANZU.py &
python3 /home/ubuntu/Desktop/NYSE/ANZUU.py &
python3 /home/ubuntu/Desktop/NYSE/ANZUW.py &
python3 /home/ubuntu/Desktop/NYSE/AOD.py &
python3 /home/ubuntu/Desktop/NYSE/AOGO.py &
python3 /home/ubuntu/Desktop/NYSE/AOGOW.py &
python3 /home/ubuntu/Desktop/NYSE/AOMR.py &
python3 /home/ubuntu/Desktop/NYSE/AON.py &
python3 /home/ubuntu/Desktop/NYSE/AORT.py &
python3 /home/ubuntu/Desktop/NYSE/AOS.py &
python3 /home/ubuntu/Desktop/NYSE/AOSL.py &
python3 /home/ubuntu/Desktop/NYSE/AOUT.py &
python3 /home/ubuntu/Desktop/NYSE/AP.py &
python3 /home/ubuntu/Desktop/NYSE/APA.py &
python3 /home/ubuntu/Desktop/NYSE/APAC.py &
python3 /home/ubuntu/Desktop/NYSE/APACW.py &
python3 /home/ubuntu/Desktop/NYSE/APAM.py &
python3 /home/ubuntu/Desktop/NYSE/APCA.py &
python3 /home/ubuntu/Desktop/NYSE/APCX.py &
python3 /home/ubuntu/Desktop/NYSE/APCXW.py &
python3 /home/ubuntu/Desktop/NYSE/APD.py &
python3 /home/ubuntu/Desktop/NYSE/APDN.py &
python3 /home/ubuntu/Desktop/NYSE/APEI.py &
python3 /home/ubuntu/Desktop/NYSE/APEN.py &
python3 /home/ubuntu/Desktop/NYSE/APG.py &
python3 /home/ubuntu/Desktop/NYSE/APGB.py &
python3 /home/ubuntu/Desktop/NYSE/APH.py &
python3 /home/ubuntu/Desktop/NYSE/API.py &
python3 /home/ubuntu/Desktop/NYSE/APLD.py &
python3 /home/ubuntu/Desktop/NYSE/APLE.py &
python3 /home/ubuntu/Desktop/NYSE/APLS.py &
python3 /home/ubuntu/Desktop/NYSE/APLT.py &
python3 /home/ubuntu/Desktop/NYSE/APM.py &
python3 /home/ubuntu/Desktop/NYSE/APMI.py &
python3 /home/ubuntu/Desktop/NYSE/APMIU.py &
python3 /home/ubuntu/Desktop/NYSE/APMIW.py &
python3 /home/ubuntu/Desktop/NYSE/APN.py &
python3 /home/ubuntu/Desktop/NYSE/APO.py &
python3 /home/ubuntu/Desktop/NYSE/APOG.py &
python3 /home/ubuntu/Desktop/NYSE/APP.py &
python3 /home/ubuntu/Desktop/NYSE/APPF.py &
python3 /home/ubuntu/Desktop/NYSE/APPH.py &
python3 /home/ubuntu/Desktop/NYSE/APPHW.py &
python3 /home/ubuntu/Desktop/NYSE/APPN.py &
python3 /home/ubuntu/Desktop/NYSE/APPS.py &
python3 /home/ubuntu/Desktop/NYSE/APRE.py &
python3 /home/ubuntu/Desktop/NYSE/APRN.py &
python3 /home/ubuntu/Desktop/NYSE/APSG.py &
python3 /home/ubuntu/Desktop/NYSE/APT.py &
python3 /home/ubuntu/Desktop/NYSE/APTMU.py &
python3 /home/ubuntu/Desktop/NYSE/APTMW.py &
python3 /home/ubuntu/Desktop/NYSE/APTO.py &
python3 /home/ubuntu/Desktop/NYSE/APTS.py &
python3 /home/ubuntu/Desktop/NYSE/APTV.py &
python3 /home/ubuntu/Desktop/NYSE/APTX.py &
python3 /home/ubuntu/Desktop/NYSE/APVO.py &
python3 /home/ubuntu/Desktop/NYSE/APWC.py &
python3 /home/ubuntu/Desktop/NYSE/APXI.py &
python3 /home/ubuntu/Desktop/NYSE/APXIU.py &
python3 /home/ubuntu/Desktop/NYSE/APXIW.py &
python3 /home/ubuntu/Desktop/NYSE/APYX.py &
python3 /home/ubuntu/Desktop/NYSE/AQB.py &
python3 /home/ubuntu/Desktop/NYSE/AQMS.py &
python3 /home/ubuntu/Desktop/NYSE/AQN.py &
python3 /home/ubuntu/Desktop/NYSE/AQNA.py &
python3 /home/ubuntu/Desktop/NYSE/AQNB.py &
python3 /home/ubuntu/Desktop/NYSE/AQNU.py &
python3 /home/ubuntu/Desktop/NYSE/AQST.py &
python3 /home/ubuntu/Desktop/NYSE/AQUA.py &
python3 /home/ubuntu/Desktop/NYSE/AR.py &
python3 /home/ubuntu/Desktop/NYSE/ARAV.py &
python3 /home/ubuntu/Desktop/NYSE/ARAY.py &
python3 /home/ubuntu/Desktop/NYSE/ARBE.py &
python3 /home/ubuntu/Desktop/NYSE/ARBEW.py &
python3 /home/ubuntu/Desktop/NYSE/ARBG.py &
python3 /home/ubuntu/Desktop/NYSE/ARBGU.py &
python3 /home/ubuntu/Desktop/NYSE/ARBGW.py &
python3 /home/ubuntu/Desktop/NYSE/ARBK.py &
python3 /home/ubuntu/Desktop/NYSE/ARC.py &
python3 /home/ubuntu/Desktop/NYSE/ARCB.py &
python3 /home/ubuntu/Desktop/NYSE/ARCC.py &
python3 /home/ubuntu/Desktop/NYSE/ARCE.py &
python3 /home/ubuntu/Desktop/NYSE/ARCH.py &
python3 /home/ubuntu/Desktop/NYSE/ARCK.py &
python3 /home/ubuntu/Desktop/NYSE/ARCKU.py &
python3 /home/ubuntu/Desktop/NYSE/ARCKW.py &
python3 /home/ubuntu/Desktop/NYSE/ARCO.py &
python3 /home/ubuntu/Desktop/NYSE/ARCT.py &
python3 /home/ubuntu/Desktop/NYSE/ARDC.py &
python3 /home/ubuntu/Desktop/NYSE/ARDS.py &
python3 /home/ubuntu/Desktop/NYSE/ARDX.py &
python3 /home/ubuntu/Desktop/NYSE/ARE.py &
python3 /home/ubuntu/Desktop/NYSE/AREB.py &
python3 /home/ubuntu/Desktop/NYSE/AREBW.py &
python3 /home/ubuntu/Desktop/NYSE/AREC.py &
python3 /home/ubuntu/Desktop/NYSE/AREN.py &
python3 /home/ubuntu/Desktop/NYSE/ARES.py &
python3 /home/ubuntu/Desktop/NYSE/ARGD.py &
python3 /home/ubuntu/Desktop/NYSE/ARGO.py &
python3 /home/ubuntu/Desktop/NYSE/ARGU.py &
python3 /home/ubuntu/Desktop/NYSE/ARGUU.py &
python3 /home/ubuntu/Desktop/NYSE/ARGUW.py &
python3 /home/ubuntu/Desktop/NYSE/ARGX.py &
python3 /home/ubuntu/Desktop/NYSE/ARHS.py &
python3 /home/ubuntu/Desktop/NYSE/ARI.py &
python3 /home/ubuntu/Desktop/NYSE/ARIS.py &
python3 /home/ubuntu/Desktop/NYSE/ARIZ.py &
python3 /home/ubuntu/Desktop/NYSE/ARIZR.py &
python3 /home/ubuntu/Desktop/NYSE/ARIZU.py &
python3 /home/ubuntu/Desktop/NYSE/ARIZW.py &
python3 /home/ubuntu/Desktop/NYSE/ARKO.py &
python3 /home/ubuntu/Desktop/NYSE/ARKOW.py &
python3 /home/ubuntu/Desktop/NYSE/ARKR.py &
python3 /home/ubuntu/Desktop/NYSE/ARL.py &
python3 /home/ubuntu/Desktop/NYSE/ARLO.py &
python3 /home/ubuntu/Desktop/NYSE/ARLP.py &
python3 /home/ubuntu/Desktop/NYSE/ARMK.py &
python3 /home/ubuntu/Desktop/NYSE/ARMP.py &
python3 /home/ubuntu/Desktop/NYSE/ARNC.py &
python3 /home/ubuntu/Desktop/NYSE/AROC.py &
python3 /home/ubuntu/Desktop/NYSE/AROW.py &
python3 /home/ubuntu/Desktop/NYSE/ARQQ.py &
python3 /home/ubuntu/Desktop/NYSE/ARQQW.py &
python3 /home/ubuntu/Desktop/NYSE/ARQT.py &
python3 /home/ubuntu/Desktop/NYSE/ARR.py &
python3 /home/ubuntu/Desktop/NYSE/ARRW.py &
python3 /home/ubuntu/Desktop/NYSE/ARRWU.py &
python3 /home/ubuntu/Desktop/NYSE/ARRWW.py &
python3 /home/ubuntu/Desktop/NYSE/ARRY.py &
python3 /home/ubuntu/Desktop/NYSE/ARTE.py &
python3 /home/ubuntu/Desktop/NYSE/ARTEW.py &
python3 /home/ubuntu/Desktop/NYSE/ARTL.py &
python3 /home/ubuntu/Desktop/NYSE/ARTLW.py &
python3 /home/ubuntu/Desktop/NYSE/ARTNA.py &
python3 /home/ubuntu/Desktop/NYSE/ARTW.py &
python3 /home/ubuntu/Desktop/NYSE/ARVL.py &
python3 /home/ubuntu/Desktop/NYSE/ARVN.py &
python3 /home/ubuntu/Desktop/NYSE/ARW.py &
python3 /home/ubuntu/Desktop/NYSE/ARWR.py &
python3 /home/ubuntu/Desktop/NYSE/ARYD.py &
python3 /home/ubuntu/Desktop/NYSE/ARYE.py &
python3 /home/ubuntu/Desktop/NYSE/ASA.py &
python3 /home/ubuntu/Desktop/NYSE/ASAI.py &
python3 /home/ubuntu/Desktop/NYSE/ASAN.py &
python3 /home/ubuntu/Desktop/NYSE/ASAQ.py &
python3 /home/ubuntu/Desktop/NYSE/ASAX.py &
python3 /home/ubuntu/Desktop/NYSE/ASB.py &
python3 /home/ubuntu/Desktop/NYSE/ASC.py &
python3 /home/ubuntu/Desktop/NYSE/ASCA.py &
python3 /home/ubuntu/Desktop/NYSE/ASCAR.py &
python3 /home/ubuntu/Desktop/NYSE/ASCBU.py &
python3 /home/ubuntu/Desktop/NYSE/ASG.py &
python3 /home/ubuntu/Desktop/NYSE/ASGI.py &
python3 /home/ubuntu/Desktop/NYSE/ASGN.py &
python3 /home/ubuntu/Desktop/NYSE/ASH.py &
python3 /home/ubuntu/Desktop/NYSE/ASIX.py &
python3 /home/ubuntu/Desktop/NYSE/ASLE.py &
python3 /home/ubuntu/Desktop/NYSE/ASLN.py &
python3 /home/ubuntu/Desktop/NYSE/ASM.py &
python3 /home/ubuntu/Desktop/NYSE/ASMB.py &
python3 /home/ubuntu/Desktop/NYSE/ASML.py &
python3 /home/ubuntu/Desktop/NYSE/ASND.py &
python3 /home/ubuntu/Desktop/NYSE/ASNS.py &
python3 /home/ubuntu/Desktop/NYSE/ASO.py &
python3 /home/ubuntu/Desktop/NYSE/ASPA.py &
python3 /home/ubuntu/Desktop/NYSE/ASPAU.py &
python3 /home/ubuntu/Desktop/NYSE/ASPAW.py &
python3 /home/ubuntu/Desktop/NYSE/ASPC.py &
python3 /home/ubuntu/Desktop/NYSE/ASPCU.py &
python3 /home/ubuntu/Desktop/NYSE/ASPCW.py &
python3 /home/ubuntu/Desktop/NYSE/ASPN.py &
python3 /home/ubuntu/Desktop/NYSE/ASPS.py &
python3 /home/ubuntu/Desktop/NYSE/ASPU.py &
python3 /home/ubuntu/Desktop/NYSE/ASR.py &
python3 /home/ubuntu/Desktop/NYSE/ASRT.py &
python3 /home/ubuntu/Desktop/NYSE/ASRV.py &
python3 /home/ubuntu/Desktop/NYSE/ASTC.py &
python3 /home/ubuntu/Desktop/NYSE/ASTE.py &
python3 /home/ubuntu/Desktop/NYSE/ASTL.py &
python3 /home/ubuntu/Desktop/NYSE/ASTLW.py &
python3 /home/ubuntu/Desktop/NYSE/ASTR.py &
python3 /home/ubuntu/Desktop/NYSE/ASTS.py &
python3 /home/ubuntu/Desktop/NYSE/ASTSW.py &
python3 /home/ubuntu/Desktop/NYSE/ASUR.py &
python3 /home/ubuntu/Desktop/NYSE/ASX.py &
python3 /home/ubuntu/Desktop/NYSE/ASXC.py &
python3 /home/ubuntu/Desktop/NYSE/ASYS.py &
python3 /home/ubuntu/Desktop/NYSE/ASZ.py &
python3 /home/ubuntu/Desktop/NYSE/ATA.py &
python3 /home/ubuntu/Desktop/NYSE/ATAI.py &
python3 /home/ubuntu/Desktop/NYSE/ATAK.py &
python3 /home/ubuntu/Desktop/NYSE/ATAKR.py &
python3 /home/ubuntu/Desktop/NYSE/ATAKU.py &
python3 /home/ubuntu/Desktop/NYSE/ATAKW.py &
python3 /home/ubuntu/Desktop/NYSE/ATAQ.py &
python3 /home/ubuntu/Desktop/NYSE/ATAX.py &
python3 /home/ubuntu/Desktop/NYSE/ATC.py &
python3 /home/ubuntu/Desktop/NYSE/ATCO.py &
python3 /home/ubuntu/Desktop/NYSE/ATCOL.py &
python3 /home/ubuntu/Desktop/NYSE/ATCX.py &
python3 /home/ubuntu/Desktop/NYSE/ATEC.py &
python3 /home/ubuntu/Desktop/NYSE/ATEK.py &
python3 /home/ubuntu/Desktop/NYSE/ATEN.py &
python3 /home/ubuntu/Desktop/NYSE/ATER.py &
python3 /home/ubuntu/Desktop/NYSE/ATEX.py &
python3 /home/ubuntu/Desktop/NYSE/ATGE.py &
python3 /home/ubuntu/Desktop/NYSE/ATHE.py &
python3 /home/ubuntu/Desktop/NYSE/ATHM.py &
python3 /home/ubuntu/Desktop/NYSE/ATHX.py &
python3 /home/ubuntu/Desktop/NYSE/ATI.py &
python3 /home/ubuntu/Desktop/NYSE/ATIF.py &
python3 /home/ubuntu/Desktop/NYSE/ATIP.py &
python3 /home/ubuntu/Desktop/NYSE/ATKR.py &
python3 /home/ubuntu/Desktop/NYSE/ATLC.py &
python3 /home/ubuntu/Desktop/NYSE/ATLCL.py &
python3 /home/ubuntu/Desktop/NYSE/ATLCP.py &
python3 /home/ubuntu/Desktop/NYSE/ATLO.py &
python3 /home/ubuntu/Desktop/NYSE/ATNF.py &
python3 /home/ubuntu/Desktop/NYSE/ATNFW.py &
python3 /home/ubuntu/Desktop/NYSE/ATNI.py &
python3 /home/ubuntu/Desktop/NYSE/ATNM.py &
python3 /home/ubuntu/Desktop/NYSE/ATNX.py &
python3 /home/ubuntu/Desktop/NYSE/ATO.py &
python3 /home/ubuntu/Desktop/NYSE/ATOM.py &
python3 /home/ubuntu/Desktop/NYSE/ATOS.py &
python3 /home/ubuntu/Desktop/NYSE/ATR.py &
python3 /home/ubuntu/Desktop/NYSE/ATRA.py &
python3 /home/ubuntu/Desktop/NYSE/ATRC.py &
python3 /home/ubuntu/Desktop/NYSE/ATRI.py &
python3 /home/ubuntu/Desktop/NYSE/ATNFW.py &
python3 /home/ubuntu/Desktop/NYSE/ATNI.py &
python3 /home/ubuntu/Desktop/NYSE/ATNM.py &
python3 /home/ubuntu/Desktop/NYSE/ATNX.py &
python3 /home/ubuntu/Desktop/NYSE/ATO.py &
python3 /home/ubuntu/Desktop/NYSE/ATOM.py &
python3 /home/ubuntu/Desktop/NYSE/ATOS.py &
python3 /home/ubuntu/Desktop/NYSE/ATR.py &
python3 /home/ubuntu/Desktop/NYSE/ATRA.py &
python3 /home/ubuntu/Desktop/NYSE/ATRC.py &
python3 /home/ubuntu/Desktop/NYSE/ATRI.py &
python3 /home/ubuntu/Desktop/NYSE/ATRO.py &
python3 /home/ubuntu/Desktop/NYSE/ATRS.py &
python3 /home/ubuntu/Desktop/NYSE/ATSG.py &
python3 /home/ubuntu/Desktop/NYSE/ATTO.py &
python3 /home/ubuntu/Desktop/NYSE/ATUS.py &
python3 /home/ubuntu/Desktop/NYSE/ATVC.py &
python3 /home/ubuntu/Desktop/NYSE/ATVCW.py &
python3 /home/ubuntu/Desktop/NYSE/ATVI.py &
python3 /home/ubuntu/Desktop/NYSE/ATXI.py &
python3 /home/ubuntu/Desktop/NYSE/ATXS.py &
python3 /home/ubuntu/Desktop/NYSE/ATY.py &
python3 /home/ubuntu/Desktop/NYSE/AU.py &
python3 /home/ubuntu/Desktop/NYSE/AUB.py &
python3 /home/ubuntu/Desktop/NYSE/AUBAP.py &
python3 /home/ubuntu/Desktop/NYSE/AUBN.py &
python3 /home/ubuntu/Desktop/NYSE/AUBN.py &
python3 /home/ubuntu/Desktop/NYSE/AUBAP.py &
python3 /home/ubuntu/Desktop/NYSE/AUD.py &
python3 /home/ubuntu/Desktop/NYSE/AUDC.py &
python3 /home/ubuntu/Desktop/NYSE/AUGX.py &
python3 /home/ubuntu/Desktop/NYSE/AUID.py &
python3 /home/ubuntu/Desktop/NYSE/AUMN.py &
python3 /home/ubuntu/Desktop/NYSE/AUPH.py &
python3 /home/ubuntu/Desktop/NYSE/AUR.py &
python3 /home/ubuntu/Desktop/NYSE/AURA.py &
python3 /home/ubuntu/Desktop/NYSE/AURC.py &
python3 /home/ubuntu/Desktop/NYSE/AURCU.py &
python3 /home/ubuntu/Desktop/NYSE/AURCW.py &
python3 /home/ubuntu/Desktop/NYSE/AUROW.py &
python3 /home/ubuntu/Desktop/NYSE/AUS.py &
python3 /home/ubuntu/Desktop/NYSE/AUST.py &
python3 /home/ubuntu/Desktop/NYSE/AUTL.py &
python3 /home/ubuntu/Desktop/NYSE/AUTO.py &
python3 /home/ubuntu/Desktop/NYSE/AUUD.py &
python3 /home/ubuntu/Desktop/NYSE/AUUDW.py &
python3 /home/ubuntu/Desktop/NYSE/AUVI.py &
python3 /home/ubuntu/Desktop/NYSE/AUVIP.py &
python3 /home/ubuntu/Desktop/NYSE/AUY.py &
python3 /home/ubuntu/Desktop/NYSE/AUVIP.py &
python3 /home/ubuntu/Desktop/NYSE/AUY.py &
python3 /home/ubuntu/Desktop/NYSE/AVA.py &
python3 /home/ubuntu/Desktop/NYSE/AVAC.py &
python3 /home/ubuntu/Desktop/NYSE/AVACW.py &
python3 /home/ubuntu/Desktop/NYSE/AVAH.py &
python3 /home/ubuntu/Desktop/NYSE/AVAL.py &
python3 /home/ubuntu/Desktop/NYSE/AVAN.py &
python3 /home/ubuntu/Desktop/NYSE/AVAV.py &
python3 /home/ubuntu/Desktop/NYSE/AVB.py &
python3 /home/ubuntu/Desktop/NYSE/AVCO.py &
python3 /home/ubuntu/Desktop/NYSE/AVCT.py &
python3 /home/ubuntu/Desktop/NYSE/AVCTW.py &
python3 /home/ubuntu/Desktop/NYSE/AVD.py &
python3 /home/ubuntu/Desktop/NYSE/AVDL.py &
python3 /home/ubuntu/Desktop/NYSE/AVDX.py &
python3 /home/ubuntu/Desktop/NYSE/AVEO.py &
python3 /home/ubuntu/Desktop/NYSE/AVGO.py &
python3 /home/ubuntu/Desktop/NYSE/AVGOP.py &
python3 /home/ubuntu/Desktop/NYSE/AVGR.py &
python3 /home/ubuntu/Desktop/NYSE/AVHI.py &
python3 /home/ubuntu/Desktop/NYSE/AVHIW.py &
python3 /home/ubuntu/Desktop/NYSE/AVID.py &
python3 /home/ubuntu/Desktop/NYSE/AVIR.py &
python3 /home/ubuntu/Desktop/NYSE/AVK.py &
python3 /home/ubuntu/Desktop/NYSE/AVLR.py &
python3 /home/ubuntu/Desktop/NYSE/AVNS.py &
python3 /home/ubuntu/Desktop/NYSE/AVNT.py &
python3 /home/ubuntu/Desktop/NYSE/AVNW.py &
python3 /home/ubuntu/Desktop/NYSE/AVO.py &
python3 /home/ubuntu/Desktop/NYSE/AVPT.py &
python3 /home/ubuntu/Desktop/NYSE/AVPTW.py &
python3 /home/ubuntu/Desktop/NYSE/AVRO.py &
python3 /home/ubuntu/Desktop/NYSE/AVT.py &
python3 /home/ubuntu/Desktop/NYSE/AVTE.py &
python3 /home/ubuntu/Desktop/NYSE/AVTR.py &
python3 /home/ubuntu/Desktop/NYSE/AVTX.py &
python3 /home/ubuntu/Desktop/NYSE/AVXL.py &
python3 /home/ubuntu/Desktop/NYSE/AVY.py &
python3 /home/ubuntu/Desktop/NYSE/AVYA.py &
python3 /home/ubuntu/Desktop/NYSE/AWF.py &
python3 /home/ubuntu/Desktop/NYSE/AWH.py &
python3 /home/ubuntu/Desktop/NYSE/AWI.py &
python3 /home/ubuntu/Desktop/NYSE/AWK.py &
python3 /home/ubuntu/Desktop/NYSE/AWP.py &
python3 /home/ubuntu/Desktop/NYSE/AWR.py &
python3 /home/ubuntu/Desktop/NYSE/AWRE.py &
python3 /home/ubuntu/Desktop/NYSE/AWX.py &
python3 /home/ubuntu/Desktop/NYSE/AX.py &
python3 /home/ubuntu/Desktop/NYSE/AXAC.py &
python3 /home/ubuntu/Desktop/NYSE/AXDX.py &
python3 /home/ubuntu/Desktop/NYSE/AXGN.py &
python3 /home/ubuntu/Desktop/NYSE/AXH.py &
python3 /home/ubuntu/Desktop/NYSE/AXL.py &
python3 /home/ubuntu/Desktop/NYSE/AXLA.py &
python3 /home/ubuntu/Desktop/NYSE/AXNX.py &
python3 /home/ubuntu/Desktop/NYSE/AXNX.py &
python3 /home/ubuntu/Desktop/NYSE/AXNX.py &
python3 /home/ubuntu/Desktop/NYSE/AXNX.py &
python3 /home/ubuntu/Desktop/NYSE/AXON.py &
python3 /home/ubuntu/Desktop/NYSE/AXP.py &
python3 /home/ubuntu/Desktop/NYSE/AXR.py &
python3 /home/ubuntu/Desktop/NYSE/AXS.py &
python3 /home/ubuntu/Desktop/NYSE/AXSM.py &
python3 /home/ubuntu/Desktop/NYSE/AXTA.py &
python3 /home/ubuntu/Desktop/NYSE/AXTI.py &
python3 /home/ubuntu/Desktop/NYSE/AXU.py &
python3 /home/ubuntu/Desktop/NYSE/AY.py &
python3 /home/ubuntu/Desktop/NYSE/AYI.py &
python3 /home/ubuntu/Desktop/NYSE/AYLA.py &
python3 /home/ubuntu/Desktop/NYSE/AYRO.py &
python3 /home/ubuntu/Desktop/NYSE/AYTU.py &
python3 /home/ubuntu/Desktop/NYSE/AYX.py &
python3 /home/ubuntu/Desktop/NYSE/AZ.py &
python3 /home/ubuntu/Desktop/NYSE/AZEK.py &
python3 /home/ubuntu/Desktop/NYSE/AZN.py &
python3 /home/ubuntu/Desktop/NYSE/AZO.py &
python3 /home/ubuntu/Desktop/NYSE/AZPN.py &
python3 /home/ubuntu/Desktop/NYSE/AZRE.py &
python3 /home/ubuntu/Desktop/NYSE/AZTA.py &
python3 /home/ubuntu/Desktop/NYSE/AZUL.py &
python3 /home/ubuntu/Desktop/NYSE/AZYO.py &
python3 /home/ubuntu/Desktop/NYSE/AZZ.py &
python3 /home/ubuntu/Desktop/NYSE/B.py &
python3 /home/ubuntu/Desktop/NYSE/BA.py &
python3 /home/ubuntu/Desktop/NYSE/BABA.py &
python3 /home/ubuntu/Desktop/NYSE/BAC.py &
python3 /home/ubuntu/Desktop/NYSE/BACA.py &
python3 /home/ubuntu/Desktop/NYSE/BAFN.py &
python3 /home/ubuntu/Desktop/NYSE/BAH.py &
python3 /home/ubuntu/Desktop/NYSE/BALL.py &
python3 /home/ubuntu/Desktop/NYSE/BAK.py &
python3 /home/ubuntu/Desktop/NYSE/BALY.py &
python3 /home/ubuntu/Desktop/NYSE/BAM.py &
python3 /home/ubuntu/Desktop/NYSE/BAMH.py &
python3 /home/ubuntu/Desktop/NYSE/BAMI.py &
python3 /home/ubuntu/Desktop/NYSE/BAMR.py &
python3 /home/ubuntu/Desktop/NYSE/BANC.py &
python3 /home/ubuntu/Desktop/NYSE/BAND.py &
python3 /home/ubuntu/Desktop/NYSE/BANF.py &
python3 /home/ubuntu/Desktop/NYSE/BANFP.py &
python3 /home/ubuntu/Desktop/NYSE/BANR.py &
python3 /home/ubuntu/Desktop/NYSE/BANX.py &
python3 /home/ubuntu/Desktop/NYSE/BAOS.py &
python3 /home/ubuntu/Desktop/NYSE/BAP.py &
python3 /home/ubuntu/Desktop/NYSE/BARK.py &
python3 /home/ubuntu/Desktop/NYSE/BASE.py &
python3 /home/ubuntu/Desktop/NYSE/BATL.py &
python3 /home/ubuntu/Desktop/NYSE/BATRA.py &
python3 /home/ubuntu/Desktop/NYSE/BATRK.py &
python3 /home/ubuntu/Desktop/NYSE/BAX.py &
python3 /home/ubuntu/Desktop/NYSE/BB.py &
python3 /home/ubuntu/Desktop/NYSE/BBAI.py &
python3 /home/ubuntu/Desktop/NYSE/BBAR.py &
python3 /home/ubuntu/Desktop/NYSE/BBBY.py &
python3 /home/ubuntu/Desktop/NYSE/BBCP.py &
python3 /home/ubuntu/Desktop/NYSE/BBD.py &
python3 /home/ubuntu/Desktop/NYSE/BBDC.py &
python3 /home/ubuntu/Desktop/NYSE/BBDO.py &
python3 /home/ubuntu/Desktop/NYSE/BBGI.py &
python3 /home/ubuntu/Desktop/NYSE/BBI.py &
python3 /home/ubuntu/Desktop/NYSE/BBIG.py &
python3 /home/ubuntu/Desktop/NYSE/BBIGV.py &
python3 /home/ubuntu/Desktop/NYSE/BBIO.py &
python3 /home/ubuntu/Desktop/NYSE/BBLG.py &
python3 /home/ubuntu/Desktop/NYSE/BBLGW.py &
python3 /home/ubuntu/Desktop/NYSE/BBLN.py &
python3 /home/ubuntu/Desktop/NYSE/BBN.py &
python3 /home/ubuntu/Desktop/NYSE/BBQ.py &
python3 /home/ubuntu/Desktop/NYSE/BBSI.py &
python3 /home/ubuntu/Desktop/NYSE/BBU.py &
python3 /home/ubuntu/Desktop/NYSE/BBUC.py &
python3 /home/ubuntu/Desktop/NYSE/BBVA.py &
python3 /home/ubuntu/Desktop/NYSE/BBW.py &
python3 /home/ubuntu/Desktop/NYSE/BBY.py &
python3 /home/ubuntu/Desktop/NYSE/BBWI.py &
python3 /home/ubuntu/Desktop/NYSE/BC.py &
python3 /home/ubuntu/Desktop/NYSE/BCAB.py &
python3 /home/ubuntu/Desktop/NYSE/BCAC.py &
python3 /home/ubuntu/Desktop/NYSE/BCACU.py &
python3 /home/ubuntu/Desktop/NYSE/BCACW.py &
python3 /home/ubuntu/Desktop/NYSE/BCAT.py &
python3 /home/ubuntu/Desktop/NYSE/BCBP.py &
python3 /home/ubuntu/Desktop/NYSE/BCC.py &
python3 /home/ubuntu/Desktop/NYSE/BCDA.py &
python3 /home/ubuntu/Desktop/NYSE/BCE.py &
python3 /home/ubuntu/Desktop/NYSE/BCEL.py &
python3 /home/ubuntu/Desktop/NYSE/BCH.py &
python3 /home/ubuntu/Desktop/NYSE/BCLI.py &
python3 /home/ubuntu/Desktop/NYSE/BCML.py &
python3 /home/ubuntu/Desktop/NYSE/BCO.py &
python3 /home/ubuntu/Desktop/NYSE/BCOR.py &
python3 /home/ubuntu/Desktop/NYSE/BCOV.py &
python3 /home/ubuntu/Desktop/NYSE/BCOW.py &
python3 /home/ubuntu/Desktop/NYSE/BCPC.py &
python3 /home/ubuntu/Desktop/NYSE/BCRX.py &
python3 /home/ubuntu/Desktop/NYSE/BCS.py &
python3 /home/ubuntu/Desktop/NYSE/BCSA.py &
python3 /home/ubuntu/Desktop/NYSE/BCSAU.py &
python3 /home/ubuntu/Desktop/NYSE/BCSAW.py &
python3 /home/ubuntu/Desktop/NYSE/BCSF.py &
python3 /home/ubuntu/Desktop/NYSE/BCTX.py &
python3 /home/ubuntu/Desktop/NYSE/BCTXW.py &
python3 /home/ubuntu/Desktop/NYSE/BCV.py &
python3 /home/ubuntu/Desktop/NYSE/BCX.py &
python3 /home/ubuntu/Desktop/NYSE/BCYC.py &
python3 /home/ubuntu/Desktop/NYSE/BDC.py &
python3 /home/ubuntu/Desktop/NYSE/BDJ.py &
python3 /home/ubuntu/Desktop/NYSE/BDL.py &
python3 /home/ubuntu/Desktop/NYSE/BDN.py &
python3 /home/ubuntu/Desktop/NYSE/BDR.py &
python3 /home/ubuntu/Desktop/NYSE/BDSX.py &
python3 /home/ubuntu/Desktop/NYSE/BDTX.py &
python3 /home/ubuntu/Desktop/NYSE/BDX.py &
python3 /home/ubuntu/Desktop/NYSE/BDXB.py &
python3 /home/ubuntu/Desktop/NYSE/BEAM.py &
python3 /home/ubuntu/Desktop/NYSE/BE.py &
python3 /home/ubuntu/Desktop/NYSE/BEAT.py &
python3 /home/ubuntu/Desktop/NYSE/BECN.py &
python3 /home/ubuntu/Desktop/NYSE/BEDU.py &
python3 /home/ubuntu/Desktop/NYSE/BEEM.py &
python3 /home/ubuntu/Desktop/NYSE/BEEMW.py &
python3 /home/ubuntu/Desktop/NYSE/BEKE.py &
python3 /home/ubuntu/Desktop/NYSE/BELFA.py &
python3 /home/ubuntu/Desktop/NYSE/BELFB.py &
python3 /home/ubuntu/Desktop/NYSE/BEN.py &
python3 /home/ubuntu/Desktop/NYSE/BENE.py &
python3 /home/ubuntu/Desktop/NYSE/BENER.py &
python3 /home/ubuntu/Desktop/NYSE/BENEW.py &
python3 /home/ubuntu/Desktop/NYSE/BEP.py &
python3 /home/ubuntu/Desktop/NYSE/BFAM.py &
python3 /home/ubuntu/Desktop/NYSE/BFC.py &
python3 /home/ubuntu/Desktop/NYSE/BFH.py &
python3 /home/ubuntu/Desktop/NYSE/BFI.py &
python3 /home/ubuntu/Desktop/NYSE/BFIIW.py &
python3 /home/ubuntu/Desktop/NYSE/BFIN.py &
python3 /home/ubuntu/Desktop/NYSE/BFK.py &
python3 /home/ubuntu/Desktop/NYSE/BFLY.py &
python3 /home/ubuntu/Desktop/NYSE/BFRI.py &
python3 /home/ubuntu/Desktop/NYSE/BFRIW.py &
python3 /home/ubuntu/Desktop/NYSE/BFS.py &
python3 /home/ubuntu/Desktop/NYSE/BEPC.py &
python3 /home/ubuntu/Desktop/NYSE/BEPH.py &
python3 /home/ubuntu/Desktop/NYSE/BEPI.py &
python3 /home/ubuntu/Desktop/NYSE/BERY.py &
python3 /home/ubuntu/Desktop/NYSE/BEST.py &
python3 /home/ubuntu/Desktop/NYSE/BFAC.py &
python3 /home/ubuntu/Desktop/NYSE/BFST.py &
python3 /home/ubuntu/Desktop/NYSE/BFZ.py &
python3 /home/ubuntu/Desktop/NYSE/BG.py &
python3 /home/ubuntu/Desktop/NYSE/BGB.py &
python3 /home/ubuntu/Desktop/NYSE/BGCP.py &
python3 /home/ubuntu/Desktop/NYSE/BGFV.py &
python3 /home/ubuntu/Desktop/NYSE/BGH.py &
python3 /home/ubuntu/Desktop/NYSE/BGI.py &
python3 /home/ubuntu/Desktop/NYSE/BGNE.py &
python3 /home/ubuntu/Desktop/NYSE/BGR.py &
python3 /home/ubuntu/Desktop/NYSE/BGRY.py &
python3 /home/ubuntu/Desktop/NYSE/BGRYW.py &
python3 /home/ubuntu/Desktop/NYSE/BGS.py &
python3 /home/ubuntu/Desktop/NYSE/BGSF.py &
python3 /home/ubuntu/Desktop/NYSE/BGSX.py &
python3 /home/ubuntu/Desktop/NYSE/BGT.py &
python3 /home/ubuntu/Desktop/NYSE/BGX.py &
python3 /home/ubuntu/Desktop/NYSE/BGXX.py &
python3 /home/ubuntu/Desktop/NYSE/BGY.py &
python3 /home/ubuntu/Desktop/NYSE/BH.py &
python3 /home/ubuntu/Desktop/NYSE/BHACU.py &
python3 /home/ubuntu/Desktop/NYSE/BHACW.py &
python3 /home/ubuntu/Desktop/NYSE/BHAT.py &
python3 /home/ubuntu/Desktop/NYSE/BHB.py &
python3 /home/ubuntu/Desktop/NYSE/BHC.py &
python3 /home/ubuntu/Desktop/NYSE/BHE.py &
python3 /home/ubuntu/Desktop/NYSE/BHF.py &
python3 /home/ubuntu/Desktop/NYSE/BHFAL.py &
python3 /home/ubuntu/Desktop/NYSE/BHFAM.py &
python3 /home/ubuntu/Desktop/NYSE/BHFAN.py &
python3 /home/ubuntu/Desktop/NYSE/BHFAO.py &
python3 /home/ubuntu/Desktop/NYSE/BHFAP.py &
python3 /home/ubuntu/Desktop/NYSE/BHG.py &
python3 /home/ubuntu/Desktop/NYSE/BHIL.py &
python3 /home/ubuntu/Desktop/NYSE/BHK.py &
python3 /home/ubuntu/Desktop/NYSE/BHLB.py &
python3 /home/ubuntu/Desktop/NYSE/BHR.py &
python3 /home/ubuntu/Desktop/NYSE/BHP.py &
python3 /home/ubuntu/Desktop/NYSE/BHSE.py &
python3 /home/ubuntu/Desktop/NYSE/BHSEU.py &
python3 /home/ubuntu/Desktop/NYSE/BHSEW.py &
python3 /home/ubuntu/Desktop/NYSE/BHV.py &
python3 /home/ubuntu/Desktop/NYSE/BHVN.py &
python3 /home/ubuntu/Desktop/NYSE/BIDU.py &
python3 /home/ubuntu/Desktop/NYSE/BIG.py &
python3 /home/ubuntu/Desktop/NYSE/BIGC.py &
python3 /home/ubuntu/Desktop/NYSE/BIGZ.py &
python3 /home/ubuntu/Desktop/NYSE/BIIB.py &
python3 /home/ubuntu/Desktop/NYSE/BILI.py &
python3 /home/ubuntu/Desktop/NYSE/BILL.py &
python3 /home/ubuntu/Desktop/NYSE/BIMI.py &
python3 /home/ubuntu/Desktop/NYSE/BIO.py &
python3 /home/ubuntu/Desktop/NYSE/BIOC.py &
python3 /home/ubuntu/Desktop/NYSE/BIOL.py &
python3 /home/ubuntu/Desktop/NYSE/BIOR.py &
python3 /home/ubuntu/Desktop/NYSE/BIOS.py &
python3 /home/ubuntu/Desktop/NYSE/BIOSU.py &
python3 /home/ubuntu/Desktop/NYSE/BIOSW.py &
python3 /home/ubuntu/Desktop/NYSE/BIOT.py &
python3 /home/ubuntu/Desktop/NYSE/BIOTU.py &
python3 /home/ubuntu/Desktop/NYSE/BIOTW.py &
python3 /home/ubuntu/Desktop/NYSE/BIOX.py &
python3 /home/ubuntu/Desktop/NYSE/BIP.py &
python3 /home/ubuntu/Desktop/NYSE/BIPC.py &
python3 /home/ubuntu/Desktop/NYSE/BIPH.py &
python3 /home/ubuntu/Desktop/NYSE/BIPI.py &
python3 /home/ubuntu/Desktop/NYSE/BIRD.py &
python3 /home/ubuntu/Desktop/NYSE/BIT.py &
python3 /home/ubuntu/Desktop/NYSE/BITE.py &
python3 /home/ubuntu/Desktop/NYSE/BITF.py &
python3 /home/ubuntu/Desktop/NYSE/BJ.py &
python3 /home/ubuntu/Desktop/NYSE/BJDX.py &
python3 /home/ubuntu/Desktop/NYSE/BJRI.py &
python3 /home/ubuntu/Desktop/NYSE/BK.py &
python3 /home/ubuntu/Desktop/NYSE/BKCC.py &
python3 /home/ubuntu/Desktop/NYSE/BKD.py &
python3 /home/ubuntu/Desktop/NYSE/BKE.py &
python3 /home/ubuntu/Desktop/NYSE/BKEP.py &
python3 /home/ubuntu/Desktop/NYSE/BKEPP.py &
python3 /home/ubuntu/Desktop/NYSE/BKH.py &
python3 /home/ubuntu/Desktop/NYSE/BKI.py &
python3 /home/ubuntu/Desktop/NYSE/BKKT.py &
python3 /home/ubuntu/Desktop/NYSE/BKN.py &
python3 /home/ubuntu/Desktop/NYSE/BKNG.py &
python3 /home/ubuntu/Desktop/NYSE/BKR.py &
python3 /home/ubuntu/Desktop/NYSE/BKSC.py &
python3 /home/ubuntu/Desktop/NYSE/BKSY.py &
python3 /home/ubuntu/Desktop/NYSE/BKT.py &
python3 /home/ubuntu/Desktop/NYSE/BKTI.py &
python3 /home/ubuntu/Desktop/NYSE/BKU.py &
python3 /home/ubuntu/Desktop/NYSE/BKYI.py &
python3 /home/ubuntu/Desktop/NYSE/BL.py &
python3 /home/ubuntu/Desktop/NYSE/BLBD.py &
python3 /home/ubuntu/Desktop/NYSE/BLBX.py &
python3 /home/ubuntu/Desktop/NYSE/BLCM.py &
python3 /home/ubuntu/Desktop/NYSE/%launcher%


